//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TareksAccount.Shared_Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuotationLine
    {
        public int Id { get; set; }
        public Nullable<int> QuotationId { get; set; }
        public Nullable<bool> IsExpense { get; set; }
        public Nullable<bool> IsProductService { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<int> Incharge { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<decimal> FC_Amount { get; set; }
        public Nullable<decimal> LC_Amount { get; set; }
        public Nullable<decimal> ClientCharge { get; set; }
    }
}
